# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
