# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_person_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
